plugins:
  - rubocop-rubycw
  - rubocop-on-rbs

AllCops:
  TargetRubyVersion: 3.4
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'bundle/**/*'
    - 'node_modules/**/*'

Style/GlobalStdStream:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/DataInheritance:
  Enabled: false

Metrics/ModuleLength:
  Max: 220

Metrics/ClassLength:
  Max: 160

Metrics/MethodLength:
  Max: 14

Metrics/BlockLength:
  Max: 32
  Exclude:
    - 'spec/**/*'

Style/ItBlockParameter:
  Enabled: false

# no frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false