plugins:
  - rubocop-rubycw
  - rubocop-on-rbs

AllCops:
  TargetRubyVersion: 3.4
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'spec/**/*'

Style/GlobalStdStream:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/DataInheritance:
  Enabled: false

Metrics/ClassLength:
  Max: 100

Metrics/MethodLength:
  Max: 10