name: Ruby

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - "3.4.4"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install dependencies (SDL)
        run: sudo apt-get install libsdl2-dev libsdl2-2.0-0 libfontconfig1-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev

      - name: Test aua
        run: bundle exec rake
      - name: List files RuboCop will inspect
        run: bundle exec rubocop -L
      - name: Run rubocop
        run: bundle exec rubocop -c .rubocop.yml --debug --format progress
