name: Ruby

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.4.4'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Test aua
        run: bundle exec rake
      - name: List files RuboCop will inspect
        run: bundle exec rubocop -L
      - name: Run rubocop
        run: bundle exec rubocop -c .rubocop.yml --debug --format progress
